DM-42165: eo_pipe/cp_verify parity: bfk
lsst/cp_verify pull request #40
Opened 2024-01-29 19:54 UTC by plazas

2024-01-29 21:35 UTC, czwa submitted a review, later dismissed
I hit approve before rereading the ticket:  this also needs to add the x-corr/y-corr slopes, doesn't it?  Those should be simple linear fits to `{flux, cov10}` and `{flux, cov01}`.

2024-01-29 21:39 UTC, czwa requested changes
Covariance slopes are missing.

2024-01-30 15:23 UTC, plazas commented
> I hit approve before rereading the ticket: this also needs to add the x-corr/y-corr slopes, doesn't it? Those should be simple linear fits to `{flux, cov10}` and `{flux, cov01}`.

Sorry for missing those, I thought we wanted to calculate them in analysis tools. The most recent commit adds these parameters.

2024-01-30 19:48 UTC, czwa approved these changes

2024-01-31 14:51 UTC, merged